# Generated by Django 3.2.8 on 2021-10-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0006_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_field',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
